//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ElstarDataSet.xsd", IsNullable=false)]
public partial class ElstarDataSet {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Button", typeof(ElstarDataSetButton))]
    [System.Xml.Serialization.XmlElementAttribute("Category", typeof(ElstarDataSetCategory))]
    [System.Xml.Serialization.XmlElementAttribute("ChainLink", typeof(ElstarDataSetChainLink))]
    [System.Xml.Serialization.XmlElementAttribute("Color", typeof(ElstarDataSetColor))]
    [System.Xml.Serialization.XmlElementAttribute("CookTimes", typeof(ElstarDataSetCookTimes))]
    [System.Xml.Serialization.XmlElementAttribute("DeviceInfo", typeof(ElstarDataSetDeviceInfo))]
    [System.Xml.Serialization.XmlElementAttribute("GroupType", typeof(ElstarDataSetGroupType))]
    [System.Xml.Serialization.XmlElementAttribute("Matrix", typeof(ElstarDataSetMatrix))]
    [System.Xml.Serialization.XmlElementAttribute("Merchandise", typeof(ElstarDataSetMerchandise))]
    [System.Xml.Serialization.XmlElementAttribute("MerchandiseDept", typeof(ElstarDataSetMerchandiseDept))]
    [System.Xml.Serialization.XmlElementAttribute("PrepOrder", typeof(ElstarDataSetPrepOrder))]
    [System.Xml.Serialization.XmlElementAttribute("Price", typeof(ElstarDataSetPrice))]
    [System.Xml.Serialization.XmlElementAttribute("PriceGroup", typeof(ElstarDataSetPriceGroup))]
    [System.Xml.Serialization.XmlElementAttribute("PrinterLocation", typeof(ElstarDataSetPrinterLocation))]
    [System.Xml.Serialization.XmlElementAttribute("Recipe", typeof(ElstarDataSetRecipe))]
    [System.Xml.Serialization.XmlElementAttribute("ScreenGroup", typeof(ElstarDataSetScreenGroup))]
    [System.Xml.Serialization.XmlElementAttribute("TaxBucket", typeof(ElstarDataSetTaxBucket))]
    [System.Xml.Serialization.XmlElementAttribute("TaxType", typeof(ElstarDataSetTaxType))]
    [System.Xml.Serialization.XmlElementAttribute("TaxXRef", typeof(ElstarDataSetTaxXRef))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
public partial class ElstarDataSetButton {
    
    private string iButtonIDField;
    
    private string iMerchandiseIDField;
    
    private string iCategoryIDField;
    
    private string iScreenGroupIDField;
    
    private string iScreenPositionField;
    
    private string iColorIDField;
    
    /// <remarks/>
    public string iButtonID {
        get {
            return this.iButtonIDField;
        }
        set {
            this.iButtonIDField = value;
        }
    }
    
    /// <remarks/>
    public string iMerchandiseID {
        get {
            return this.iMerchandiseIDField;
        }
        set {
            this.iMerchandiseIDField = value;
        }
    }
    
    /// <remarks/>
    public string iCategoryID {
        get {
            return this.iCategoryIDField;
        }
        set {
            this.iCategoryIDField = value;
        }
    }
    
    /// <remarks/>
    public string iScreenGroupID {
        get {
            return this.iScreenGroupIDField;
        }
        set {
            this.iScreenGroupIDField = value;
        }
    }
    
    /// <remarks/>
    public string iScreenPosition {
        get {
            return this.iScreenPositionField;
        }
        set {
            this.iScreenPositionField = value;
        }
    }
    
    /// <remarks/>
    public string iColorID {
        get {
            return this.iColorIDField;
        }
        set {
            this.iColorIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
public partial class ElstarDataSetCategory {
    
    private string iCategoryIDField;
    
    private string iPrintOrderField;
    
    private string sNameField;
    
    private string bActiveField;
    
    /// <remarks/>
    public string iCategoryID {
        get {
            return this.iCategoryIDField;
        }
        set {
            this.iCategoryIDField = value;
        }
    }
    
    /// <remarks/>
    public string iPrintOrder {
        get {
            return this.iPrintOrderField;
        }
        set {
            this.iPrintOrderField = value;
        }
    }
    
    /// <remarks/>
    public string sName {
        get {
            return this.sNameField;
        }
        set {
            this.sNameField = value;
        }
    }
    
    /// <remarks/>
    public string bActive {
        get {
            return this.bActiveField;
        }
        set {
            this.bActiveField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
public partial class ElstarDataSetChainLink {
    
    private string iChainLinkIDField;
    
    private string iSequenceField;
    
    private string iButtonIDField;
    
    private string iScreenGroupIDField;
    
    private string iMinRequiredField;
    
    private string iMaxRequiredField;
    
    /// <remarks/>
    public string iChainLinkID {
        get {
            return this.iChainLinkIDField;
        }
        set {
            this.iChainLinkIDField = value;
        }
    }
    
    /// <remarks/>
    public string iSequence {
        get {
            return this.iSequenceField;
        }
        set {
            this.iSequenceField = value;
        }
    }
    
    /// <remarks/>
    public string iButtonID {
        get {
            return this.iButtonIDField;
        }
        set {
            this.iButtonIDField = value;
        }
    }
    
    /// <remarks/>
    public string iScreenGroupID {
        get {
            return this.iScreenGroupIDField;
        }
        set {
            this.iScreenGroupIDField = value;
        }
    }
    
    /// <remarks/>
    public string iMinRequired {
        get {
            return this.iMinRequiredField;
        }
        set {
            this.iMinRequiredField = value;
        }
    }
    
    /// <remarks/>
    public string iMaxRequired {
        get {
            return this.iMaxRequiredField;
        }
        set {
            this.iMaxRequiredField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
public partial class ElstarDataSetColor {
    
    private string iColorIDField;
    
    private string sNameField;
    
    private string iVBColorCodeField;
    
    /// <remarks/>
    public string iColorID {
        get {
            return this.iColorIDField;
        }
        set {
            this.iColorIDField = value;
        }
    }
    
    /// <remarks/>
    public string sName {
        get {
            return this.sNameField;
        }
        set {
            this.sNameField = value;
        }
    }
    
    /// <remarks/>
    public string iVBColorCode {
        get {
            return this.iVBColorCodeField;
        }
        set {
            this.iVBColorCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
public partial class ElstarDataSetCookTimes {
    
    private string iCookTimeIDField;
    
    private string iCookTimeMinutesField;
    
    private string dtModifiedDateField;
    
    private string sDescField;
    
    /// <remarks/>
    public string iCookTimeID {
        get {
            return this.iCookTimeIDField;
        }
        set {
            this.iCookTimeIDField = value;
        }
    }
    
    /// <remarks/>
    public string iCookTimeMinutes {
        get {
            return this.iCookTimeMinutesField;
        }
        set {
            this.iCookTimeMinutesField = value;
        }
    }
    
    /// <remarks/>
    public string dtModifiedDate {
        get {
            return this.dtModifiedDateField;
        }
        set {
            this.dtModifiedDateField = value;
        }
    }
    
    /// <remarks/>
    public string sDesc {
        get {
            return this.sDescField;
        }
        set {
            this.sDescField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
public partial class ElstarDataSetDeviceInfo {
    
    private string iDeviceInfoIDField;
    
    private string sDeviceNameField;
    
    private string iDeviceTypeField;
    
    private string sPrinterPortField;
    
    private string iTerminalIDField;
    
    private string iRedirectToField;
    
    private string iRedirectTimeoutField;
    
    private string iManualRedirectToField;
    
    private string sLogoStringField;
    
    private string bCutReDirectedChitField;
    
    private string bColorPrinterField;
    
    private string bOPOSField;
    
    private string bSerialCashField;
    
    private string bLocalField;
    
    private string iHeaderLinesField;
    
    private string iTrailerLinesField;
    
    private string bKDSDeviceField;
    
    private string bConfiguredField;
    
    private string sDriverNameField;
    
    private string iMenuPrintDestIDField;
    
    /// <remarks/>
    public string iDeviceInfoID {
        get {
            return this.iDeviceInfoIDField;
        }
        set {
            this.iDeviceInfoIDField = value;
        }
    }
    
    /// <remarks/>
    public string sDeviceName {
        get {
            return this.sDeviceNameField;
        }
        set {
            this.sDeviceNameField = value;
        }
    }
    
    /// <remarks/>
    public string iDeviceType {
        get {
            return this.iDeviceTypeField;
        }
        set {
            this.iDeviceTypeField = value;
        }
    }
    
    /// <remarks/>
    public string sPrinterPort {
        get {
            return this.sPrinterPortField;
        }
        set {
            this.sPrinterPortField = value;
        }
    }
    
    /// <remarks/>
    public string iTerminalID {
        get {
            return this.iTerminalIDField;
        }
        set {
            this.iTerminalIDField = value;
        }
    }
    
    /// <remarks/>
    public string iRedirectTo {
        get {
            return this.iRedirectToField;
        }
        set {
            this.iRedirectToField = value;
        }
    }
    
    /// <remarks/>
    public string iRedirectTimeout {
        get {
            return this.iRedirectTimeoutField;
        }
        set {
            this.iRedirectTimeoutField = value;
        }
    }
    
    /// <remarks/>
    public string iManualRedirectTo {
        get {
            return this.iManualRedirectToField;
        }
        set {
            this.iManualRedirectToField = value;
        }
    }
    
    /// <remarks/>
    public string sLogoString {
        get {
            return this.sLogoStringField;
        }
        set {
            this.sLogoStringField = value;
        }
    }
    
    /// <remarks/>
    public string bCutReDirectedChit {
        get {
            return this.bCutReDirectedChitField;
        }
        set {
            this.bCutReDirectedChitField = value;
        }
    }
    
    /// <remarks/>
    public string bColorPrinter {
        get {
            return this.bColorPrinterField;
        }
        set {
            this.bColorPrinterField = value;
        }
    }
    
    /// <remarks/>
    public string bOPOS {
        get {
            return this.bOPOSField;
        }
        set {
            this.bOPOSField = value;
        }
    }
    
    /// <remarks/>
    public string bSerialCash {
        get {
            return this.bSerialCashField;
        }
        set {
            this.bSerialCashField = value;
        }
    }
    
    /// <remarks/>
    public string bLocal {
        get {
            return this.bLocalField;
        }
        set {
            this.bLocalField = value;
        }
    }
    
    /// <remarks/>
    public string iHeaderLines {
        get {
            return this.iHeaderLinesField;
        }
        set {
            this.iHeaderLinesField = value;
        }
    }
    
    /// <remarks/>
    public string iTrailerLines {
        get {
            return this.iTrailerLinesField;
        }
        set {
            this.iTrailerLinesField = value;
        }
    }
    
    /// <remarks/>
    public string bKDSDevice {
        get {
            return this.bKDSDeviceField;
        }
        set {
            this.bKDSDeviceField = value;
        }
    }
    
    /// <remarks/>
    public string bConfigured {
        get {
            return this.bConfiguredField;
        }
        set {
            this.bConfiguredField = value;
        }
    }
    
    /// <remarks/>
    public string sDriverName {
        get {
            return this.sDriverNameField;
        }
        set {
            this.sDriverNameField = value;
        }
    }
    
    /// <remarks/>
    public string iMenuPrintDestID {
        get {
            return this.iMenuPrintDestIDField;
        }
        set {
            this.iMenuPrintDestIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
public partial class ElstarDataSetGroupType {
    
    private string iGroupTypeIDField;
    
    private string sNameField;
    
    private string sDescField;
    
    /// <remarks/>
    public string iGroupTypeID {
        get {
            return this.iGroupTypeIDField;
        }
        set {
            this.iGroupTypeIDField = value;
        }
    }
    
    /// <remarks/>
    public string sName {
        get {
            return this.sNameField;
        }
        set {
            this.sNameField = value;
        }
    }
    
    /// <remarks/>
    public string sDesc {
        get {
            return this.sDescField;
        }
        set {
            this.sDescField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
public partial class ElstarDataSetMatrix {
    
    private string iMatrixIDField;
    
    private string sDisplayNameField;
    
    private string bKeepOldField;
    
    private string sCommentField;
    
    private string bVisableField;
    
    private string iFieldIndexField;
    
    /// <remarks/>
    public string iMatrixID {
        get {
            return this.iMatrixIDField;
        }
        set {
            this.iMatrixIDField = value;
        }
    }
    
    /// <remarks/>
    public string sDisplayName {
        get {
            return this.sDisplayNameField;
        }
        set {
            this.sDisplayNameField = value;
        }
    }
    
    /// <remarks/>
    public string bKeepOld {
        get {
            return this.bKeepOldField;
        }
        set {
            this.bKeepOldField = value;
        }
    }
    
    /// <remarks/>
    public string sComment {
        get {
            return this.sCommentField;
        }
        set {
            this.sCommentField = value;
        }
    }
    
    /// <remarks/>
    public string bVisable {
        get {
            return this.bVisableField;
        }
        set {
            this.bVisableField = value;
        }
    }
    
    /// <remarks/>
    public string iFieldIndex {
        get {
            return this.iFieldIndexField;
        }
        set {
            this.iFieldIndexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
public partial class ElstarDataSetMerchandise {
    
    private string iMerchandiseIDField;
    
    private string iPriceGroupIDField;
    
    private string iMerchandiseDeptIDField;
    
    private string iAiiNumField;
    
    private string sItemNameField;
    
    private string sOrderNameField;
    
    private string iCookTimeField;
    
    private string iPrepOrderField;
    
    private string iQtyAvailField;
    
    private string bIsModifierField;
    
    private string bIsLockedField;
    
    private string bIsDailyField;
    
    private string bPrintSameLineField;
    
    private string bForceRecipeField;
    
    private string bNotSoldField;
    
    private string bPromptForPriceField;
    
    private string bPrintOnOrderField;
    
    private string bPrintOnReceiptField;
    
    private string bIgnoreItemField;
    
    private string bPrintRecipeField;
    
    private string bBeverageField;
    
    private string bEntreAppetizerField;
    
    private string bDeletedField;
    
    private string dtModifiedField;
    
    private string bGroupingItemField;
    
    private string bPrintGroupItemsField;
    
    private string bAllowPartialSendField;
    
    /// <remarks/>
    public string iMerchandiseID {
        get {
            return this.iMerchandiseIDField;
        }
        set {
            this.iMerchandiseIDField = value;
        }
    }
    
    /// <remarks/>
    public string iPriceGroupID {
        get {
            return this.iPriceGroupIDField;
        }
        set {
            this.iPriceGroupIDField = value;
        }
    }
    
    /// <remarks/>
    public string iMerchandiseDeptID {
        get {
            return this.iMerchandiseDeptIDField;
        }
        set {
            this.iMerchandiseDeptIDField = value;
        }
    }
    
    /// <remarks/>
    public string iAiiNum {
        get {
            return this.iAiiNumField;
        }
        set {
            this.iAiiNumField = value;
        }
    }
    
    /// <remarks/>
    public string sItemName {
        get {
            return this.sItemNameField;
        }
        set {
            this.sItemNameField = value;
        }
    }
    
    /// <remarks/>
    public string sOrderName {
        get {
            return this.sOrderNameField;
        }
        set {
            this.sOrderNameField = value;
        }
    }
    
    /// <remarks/>
    public string iCookTime {
        get {
            return this.iCookTimeField;
        }
        set {
            this.iCookTimeField = value;
        }
    }
    
    /// <remarks/>
    public string iPrepOrder {
        get {
            return this.iPrepOrderField;
        }
        set {
            this.iPrepOrderField = value;
        }
    }
    
    /// <remarks/>
    public string iQtyAvail {
        get {
            return this.iQtyAvailField;
        }
        set {
            this.iQtyAvailField = value;
        }
    }
    
    /// <remarks/>
    public string bIsModifier {
        get {
            return this.bIsModifierField;
        }
        set {
            this.bIsModifierField = value;
        }
    }
    
    /// <remarks/>
    public string bIsLocked {
        get {
            return this.bIsLockedField;
        }
        set {
            this.bIsLockedField = value;
        }
    }
    
    /// <remarks/>
    public string bIsDaily {
        get {
            return this.bIsDailyField;
        }
        set {
            this.bIsDailyField = value;
        }
    }
    
    /// <remarks/>
    public string bPrintSameLine {
        get {
            return this.bPrintSameLineField;
        }
        set {
            this.bPrintSameLineField = value;
        }
    }
    
    /// <remarks/>
    public string bForceRecipe {
        get {
            return this.bForceRecipeField;
        }
        set {
            this.bForceRecipeField = value;
        }
    }
    
    /// <remarks/>
    public string bNotSold {
        get {
            return this.bNotSoldField;
        }
        set {
            this.bNotSoldField = value;
        }
    }
    
    /// <remarks/>
    public string bPromptForPrice {
        get {
            return this.bPromptForPriceField;
        }
        set {
            this.bPromptForPriceField = value;
        }
    }
    
    /// <remarks/>
    public string bPrintOnOrder {
        get {
            return this.bPrintOnOrderField;
        }
        set {
            this.bPrintOnOrderField = value;
        }
    }
    
    /// <remarks/>
    public string bPrintOnReceipt {
        get {
            return this.bPrintOnReceiptField;
        }
        set {
            this.bPrintOnReceiptField = value;
        }
    }
    
    /// <remarks/>
    public string bIgnoreItem {
        get {
            return this.bIgnoreItemField;
        }
        set {
            this.bIgnoreItemField = value;
        }
    }
    
    /// <remarks/>
    public string bPrintRecipe {
        get {
            return this.bPrintRecipeField;
        }
        set {
            this.bPrintRecipeField = value;
        }
    }
    
    /// <remarks/>
    public string bBeverage {
        get {
            return this.bBeverageField;
        }
        set {
            this.bBeverageField = value;
        }
    }
    
    /// <remarks/>
    public string bEntreAppetizer {
        get {
            return this.bEntreAppetizerField;
        }
        set {
            this.bEntreAppetizerField = value;
        }
    }
    
    /// <remarks/>
    public string bDeleted {
        get {
            return this.bDeletedField;
        }
        set {
            this.bDeletedField = value;
        }
    }
    
    /// <remarks/>
    public string dtModified {
        get {
            return this.dtModifiedField;
        }
        set {
            this.dtModifiedField = value;
        }
    }
    
    /// <remarks/>
    public string bGroupingItem {
        get {
            return this.bGroupingItemField;
        }
        set {
            this.bGroupingItemField = value;
        }
    }
    
    /// <remarks/>
    public string bPrintGroupItems {
        get {
            return this.bPrintGroupItemsField;
        }
        set {
            this.bPrintGroupItemsField = value;
        }
    }
    
    /// <remarks/>
    public string bAllowPartialSend {
        get {
            return this.bAllowPartialSendField;
        }
        set {
            this.bAllowPartialSendField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
public partial class ElstarDataSetMerchandiseDept {
    
    private string sNameField;
    
    private string iMerchandiseDeptIDField;
    
    private string iTipableField;
    
    private string bActiveField;
    
    private string bVATTaxField;
    
    private string bPriceIncludesTaxField;
    
    /// <remarks/>
    public string sName {
        get {
            return this.sNameField;
        }
        set {
            this.sNameField = value;
        }
    }
    
    /// <remarks/>
    public string iMerchandiseDeptID {
        get {
            return this.iMerchandiseDeptIDField;
        }
        set {
            this.iMerchandiseDeptIDField = value;
        }
    }
    
    /// <remarks/>
    public string iTipable {
        get {
            return this.iTipableField;
        }
        set {
            this.iTipableField = value;
        }
    }
    
    /// <remarks/>
    public string bActive {
        get {
            return this.bActiveField;
        }
        set {
            this.bActiveField = value;
        }
    }
    
    /// <remarks/>
    public string bVATTax {
        get {
            return this.bVATTaxField;
        }
        set {
            this.bVATTaxField = value;
        }
    }
    
    /// <remarks/>
    public string bPriceIncludesTax {
        get {
            return this.bPriceIncludesTaxField;
        }
        set {
            this.bPriceIncludesTaxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
public partial class ElstarDataSetPrepOrder {
    
    private string iPrepOrderIDField;
    
    private string sNameField;
    
    /// <remarks/>
    public string iPrepOrderID {
        get {
            return this.iPrepOrderIDField;
        }
        set {
            this.iPrepOrderIDField = value;
        }
    }
    
    /// <remarks/>
    public string sName {
        get {
            return this.sNameField;
        }
        set {
            this.sNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
public partial class ElstarDataSetPrice {
    
    private string iPriceIDField;
    
    private string iPriceDescIDField;
    
    private string iAmountField;
    
    private string iDayOnField;
    
    private string dtTimeOnField;
    
    private string dtTimeOffField;
    
    private string iButtonIDField;
    
    private string iGroupTypeIDField;
    
    /// <remarks/>
    public string iPriceID {
        get {
            return this.iPriceIDField;
        }
        set {
            this.iPriceIDField = value;
        }
    }
    
    /// <remarks/>
    public string iPriceDescID {
        get {
            return this.iPriceDescIDField;
        }
        set {
            this.iPriceDescIDField = value;
        }
    }
    
    /// <remarks/>
    public string iAmount {
        get {
            return this.iAmountField;
        }
        set {
            this.iAmountField = value;
        }
    }
    
    /// <remarks/>
    public string iDayOn {
        get {
            return this.iDayOnField;
        }
        set {
            this.iDayOnField = value;
        }
    }
    
    /// <remarks/>
    public string dtTimeOn {
        get {
            return this.dtTimeOnField;
        }
        set {
            this.dtTimeOnField = value;
        }
    }
    
    /// <remarks/>
    public string dtTimeOff {
        get {
            return this.dtTimeOffField;
        }
        set {
            this.dtTimeOffField = value;
        }
    }
    
    /// <remarks/>
    public string iButtonID {
        get {
            return this.iButtonIDField;
        }
        set {
            this.iButtonIDField = value;
        }
    }
    
    /// <remarks/>
    public string iGroupTypeID {
        get {
            return this.iGroupTypeIDField;
        }
        set {
            this.iGroupTypeIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
public partial class ElstarDataSetPriceGroup {
    
    private string iPriceGroupIDField;
    
    private string sNameField;
    
    private string bActiveField;
    
    /// <remarks/>
    public string iPriceGroupID {
        get {
            return this.iPriceGroupIDField;
        }
        set {
            this.iPriceGroupIDField = value;
        }
    }
    
    /// <remarks/>
    public string sName {
        get {
            return this.sNameField;
        }
        set {
            this.sNameField = value;
        }
    }
    
    /// <remarks/>
    public string bActive {
        get {
            return this.bActiveField;
        }
        set {
            this.bActiveField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
public partial class ElstarDataSetPrinterLocation {
    
    private string iPrinterLocIDField;
    
    private string iMerchandiseIDField;
    
    private string iDeviceInfoIDField;
    
    private string iSequenceField;
    
    /// <remarks/>
    public string iPrinterLocID {
        get {
            return this.iPrinterLocIDField;
        }
        set {
            this.iPrinterLocIDField = value;
        }
    }
    
    /// <remarks/>
    public string iMerchandiseID {
        get {
            return this.iMerchandiseIDField;
        }
        set {
            this.iMerchandiseIDField = value;
        }
    }
    
    /// <remarks/>
    public string iDeviceInfoID {
        get {
            return this.iDeviceInfoIDField;
        }
        set {
            this.iDeviceInfoIDField = value;
        }
    }
    
    /// <remarks/>
    public string iSequence {
        get {
            return this.iSequenceField;
        }
        set {
            this.iSequenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
public partial class ElstarDataSetRecipe {
    
    private string iRecipeIDField;
    
    private string iMerchandiseIDField;
    
    private string iSequenceField;
    
    private string sTextField;
    
    /// <remarks/>
    public string iRecipeID {
        get {
            return this.iRecipeIDField;
        }
        set {
            this.iRecipeIDField = value;
        }
    }
    
    /// <remarks/>
    public string iMerchandiseID {
        get {
            return this.iMerchandiseIDField;
        }
        set {
            this.iMerchandiseIDField = value;
        }
    }
    
    /// <remarks/>
    public string iSequence {
        get {
            return this.iSequenceField;
        }
        set {
            this.iSequenceField = value;
        }
    }
    
    /// <remarks/>
    public string sText {
        get {
            return this.sTextField;
        }
        set {
            this.sTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
public partial class ElstarDataSetScreenGroup {
    
    private string iScreenGroupIDField;
    
    private string sNameField;
    
    private string iScreenPositionField;
    
    private string iAutoSortField;
    
    private string bActiveField;
    
    private string bIsDirtyField;
    
    /// <remarks/>
    public string iScreenGroupID {
        get {
            return this.iScreenGroupIDField;
        }
        set {
            this.iScreenGroupIDField = value;
        }
    }
    
    /// <remarks/>
    public string sName {
        get {
            return this.sNameField;
        }
        set {
            this.sNameField = value;
        }
    }
    
    /// <remarks/>
    public string iScreenPosition {
        get {
            return this.iScreenPositionField;
        }
        set {
            this.iScreenPositionField = value;
        }
    }
    
    /// <remarks/>
    public string iAutoSort {
        get {
            return this.iAutoSortField;
        }
        set {
            this.iAutoSortField = value;
        }
    }
    
    /// <remarks/>
    public string bActive {
        get {
            return this.bActiveField;
        }
        set {
            this.bActiveField = value;
        }
    }
    
    /// <remarks/>
    public string bIsDirty {
        get {
            return this.bIsDirtyField;
        }
        set {
            this.bIsDirtyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
public partial class ElstarDataSetTaxBucket {
    
    private string iTaxBucketIDField;
    
    private string sDescriptionField;
    
    /// <remarks/>
    public string iTaxBucketID {
        get {
            return this.iTaxBucketIDField;
        }
        set {
            this.iTaxBucketIDField = value;
        }
    }
    
    /// <remarks/>
    public string sDescription {
        get {
            return this.sDescriptionField;
        }
        set {
            this.sDescriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
public partial class ElstarDataSetTaxType {
    
    private string iTaxTypeIDField;
    
    private string sNameField;
    
    private string iTaxBucketIDField;
    
    /// <remarks/>
    public string iTaxTypeID {
        get {
            return this.iTaxTypeIDField;
        }
        set {
            this.iTaxTypeIDField = value;
        }
    }
    
    /// <remarks/>
    public string sName {
        get {
            return this.sNameField;
        }
        set {
            this.sNameField = value;
        }
    }
    
    /// <remarks/>
    public string iTaxBucketID {
        get {
            return this.iTaxBucketIDField;
        }
        set {
            this.iTaxBucketIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ElstarDataSet.xsd")]
public partial class ElstarDataSetTaxXRef {
    
    private string iMerchandiseIDField;
    
    private string iTaxTypeIDField;
    
    /// <remarks/>
    public string iMerchandiseID {
        get {
            return this.iMerchandiseIDField;
        }
        set {
            this.iMerchandiseIDField = value;
        }
    }
    
    /// <remarks/>
    public string iTaxTypeID {
        get {
            return this.iTaxTypeIDField;
        }
        set {
            this.iTaxTypeIDField = value;
        }
    }
}
