//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A1ToCatalogMenuLoader
{
    using System;
    using System.Collections.Generic;
    
    public partial class Button
    {
        public int iButtonID { get; set; }
        public int iMerchandiseID { get; set; }
        public int iCategoryID { get; set; }
        public int iScreenGroupID { get; set; }
        public int iScreenPosition { get; set; }
        public int iColorID { get; set; }
        public int iGroupTypeID { get; set; }
        public int iItemTierID { get; set; }
        public string CostCenter { get; set; }
    }
}
