//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A1ToCatalogMenuLoader
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class APBMenuCatalogEntities : DbContext
    {
        public APBMenuCatalogEntities()
            : base("name=APBMenuCatalogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Button> Buttons { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ChainLink> ChainLinks { get; set; }
        public virtual DbSet<GroupType> GroupTypes { get; set; }
        public virtual DbSet<Merchandise> Merchandises { get; set; }
        public virtual DbSet<MerchandiseDept> MerchandiseDepts { get; set; }
        public virtual DbSet<PrepOrder> PrepOrders { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<PriceDesc> PriceDescs { get; set; }
        public virtual DbSet<ScreenGroup> ScreenGroups { get; set; }
    
        public virtual int PurgeLandRestaurantData(string restNumber)
        {
            var restNumberParameter = restNumber != null ?
                new ObjectParameter("RestNumber", restNumber) :
                new ObjectParameter("RestNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PurgeLandRestaurantData", restNumberParameter);
        }
    }
}
