//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A1ToCatalogMenuLoader
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChainLink
    {
        public int iChainLinkID { get; set; }
        public int iSequence { get; set; }
        public int iButtonID { get; set; }
        public int iScreenGroupID { get; set; }
        public int iMinRequired { get; set; }
        public int iMaxRequired { get; set; }
        public string CostCenter { get; set; }
    }
}
