//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A1ToCatalogMenuLoader
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int iPriceID { get; set; }
        public int iPriceDescID { get; set; }
        public decimal iAmount { get; set; }
        public int iDayOn { get; set; }
        public System.DateTime dtTimeOn { get; set; }
        public Nullable<System.DateTime> dtTimeOff { get; set; }
        public int iButtonID { get; set; }
        public int iGroupTypeID { get; set; }
        public Nullable<int> iWeight { get; set; }
        public string CostCenter { get; set; }
    }
}
