//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A1ToCatalogMenuLoader
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreenGroup
    {
        public int iScreenGroupID { get; set; }
        public int iScreenPosition { get; set; }
        public string sName { get; set; }
        public int iAutoSort { get; set; }
        public bool bActive { get; set; }
        public string CostCenter { get; set; }
    }
}
