//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpComponentsLoader
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class APBMenuCatalogEntities : DbContext
    {
        public APBMenuCatalogEntities()
            : base("name=APBMenuCatalogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Component> Components { get; set; }
        public virtual DbSet<ComponentGroup> ComponentGroups { get; set; }
        public virtual DbSet<MenuCatalogItem> MenuCatalogItems { get; set; }
        public virtual DbSet<vwMenuItemCategoryModifierMap> vwMenuItemCategoryModifierMaps { get; set; }
    
        public virtual int CreateComponentGroup(string componentGroupName, Nullable<int> min, Nullable<int> max, Nullable<int> menuCatalogItemID, Nullable<int> sequence, string componentGroupNameList, string maxList, string minList, string details, string componentIDList)
        {
            var componentGroupNameParameter = componentGroupName != null ?
                new ObjectParameter("ComponentGroupName", componentGroupName) :
                new ObjectParameter("ComponentGroupName", typeof(string));
    
            var minParameter = min.HasValue ?
                new ObjectParameter("Min", min) :
                new ObjectParameter("Min", typeof(int));
    
            var maxParameter = max.HasValue ?
                new ObjectParameter("Max", max) :
                new ObjectParameter("Max", typeof(int));
    
            var menuCatalogItemIDParameter = menuCatalogItemID.HasValue ?
                new ObjectParameter("MenuCatalogItemID", menuCatalogItemID) :
                new ObjectParameter("MenuCatalogItemID", typeof(int));
    
            var sequenceParameter = sequence.HasValue ?
                new ObjectParameter("Sequence", sequence) :
                new ObjectParameter("Sequence", typeof(int));
    
            var componentGroupNameListParameter = componentGroupNameList != null ?
                new ObjectParameter("ComponentGroupNameList", componentGroupNameList) :
                new ObjectParameter("ComponentGroupNameList", typeof(string));
    
            var maxListParameter = maxList != null ?
                new ObjectParameter("MaxList", maxList) :
                new ObjectParameter("MaxList", typeof(string));
    
            var minListParameter = minList != null ?
                new ObjectParameter("MinList", minList) :
                new ObjectParameter("MinList", typeof(string));
    
            var detailsParameter = details != null ?
                new ObjectParameter("Details", details) :
                new ObjectParameter("Details", typeof(string));
    
            var componentIDListParameter = componentIDList != null ?
                new ObjectParameter("ComponentIDList", componentIDList) :
                new ObjectParameter("ComponentIDList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateComponentGroup", componentGroupNameParameter, minParameter, maxParameter, menuCatalogItemIDParameter, sequenceParameter, componentGroupNameListParameter, maxListParameter, minListParameter, detailsParameter, componentIDListParameter);
        }
    }
}
