//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpComponentsLoader
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuCatalogItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuCatalogItem()
        {
            this.Components = new HashSet<Component>();
            this.ComponentGroups = new HashSet<ComponentGroup>();
        }
    
        public int MenuCatalogItemID { get; set; }
        public int AiiNum { get; set; }
        public string MenuItemName { get; set; }
        public string MenuItemName2 { get; set; }
        public int MenuItemClassificationID { get; set; }
        public Nullable<int> ComboTypeID { get; set; }
        public bool IsModifier { get; set; }
        public int MenuItemCategoryID { get; set; }
        public bool Active { get; set; }
        public bool IsCombo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Component> Components { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComponentGroup> ComponentGroups { get; set; }
    }
}
