//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpComponentsLoader
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMenuItemCategoryModifierMap
    {
        public int MenuCatalogItemID { get; set; }
        public int BrandAiiNum { get; set; }
        public int Sequence { get; set; }
        public int Min { get; set; }
        public int Max { get; set; }
        public string CondimentGroup { get; set; }
        public int BrandModMenuCatalogItemID { get; set; }
        public int BrandModAii { get; set; }
        public int InUseRestaurantsCount { get; set; }
    }
}
